// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-07-06 17:45:08.845757 +0100 WAT m=+0.033483725

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Alao ramon Adebisi",
            "email": "alao.adebusy@gmail.com"
        },
        "license": {
            "name": "Linear Logic Concept",
            "url": "https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/Users/ChangeUserDetails/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new question",
                "parameters": [
                    {
                        "description": "create new user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/Users/ChangeUserStatus/{Username}/{Status}/{RoleID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Update user status ('Active', 'Non-Active')",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/Users/CreateUser/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new question",
                "parameters": [
                    {
                        "description": "create new user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/Users/FetchAvailableRoles/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new question",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Roles"
                        }
                    }
                }
            }
        },
        "/api/Users/GetUserFullInfoByEmail/{UserEmail}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "get user detials by user email address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email address",
                        "name": "UserEmail",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/api/complaint/CreateComplaintCategories/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new compliant category",
                "parameters": [
                    {
                        "description": "Create new complaint category",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ComplaintCategories"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/complaint/CreateComplaintSubCategories/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new compliant sub category",
                "parameters": [
                    {
                        "description": "Create new complaint sub category",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ComplaintSubCategories"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/complaint/FetchComplaintCategories/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "fetch the list of complaint category",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TblComplaintCategories"
                        }
                    }
                }
            }
        },
        "/api/complaint/FetchComplaintSubCategories/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "fetch the list of complaint sub-category",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TblComplaintSubCategories"
                        }
                    }
                }
            }
        },
        "/api/complaint/GetComplaintByRefID/{ReferenceID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "get logged complaint with reference ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TblCases"
                        }
                    }
                }
            }
        },
        "/api/complaint/LogComplaintRequest/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "create new compliant",
                "parameters": [
                    {
                        "description": "Create new complaint",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Cases"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Cases": {
            "type": "object",
            "properties": {
                "AccountCurrency": {
                    "type": "string"
                },
                "AccountNumber": {
                    "type": "string"
                },
                "AccountType": {
                    "type": "string"
                },
                "ActionTaken": {
                    "type": "string"
                },
                "AddedBy": {
                    "type": "string"
                },
                "Address1": {
                    "type": "string"
                },
                "Address2": {
                    "type": "string"
                },
                "AmountRecovered": {
                    "description": "decimal.Decimal",
                    "type": "string"
                },
                "AmountRefunded": {
                    "description": "decimal.Decimal",
                    "type": "string"
                },
                "BranchName": {
                    "type": "string"
                },
                "CFirstName": {
                    "type": "string"
                },
                "CLastName": {
                    "type": "string"
                },
                "CMiddleName": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                },
                "CellPhone": {
                    "type": "string"
                },
                "City": {
                    "type": "string"
                },
                "ClientType": {
                    "type": "string"
                },
                "ComplaintChannelID": {
                    "type": "string"
                },
                "ComplaintLocation": {
                    "type": "string"
                },
                "ComplaintType": {
                    "type": "string"
                },
                "Country": {
                    "type": "string"
                },
                "DateReceived": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "DisputeAmount": {
                    "description": "decimal.Decimal",
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FullName": {
                    "type": "string"
                },
                "Implication": {
                    "type": "string"
                },
                "NameOfConsultant": {
                    "type": "string"
                },
                "OfficePhone": {
                    "type": "string"
                },
                "PosterCode": {
                    "type": "string"
                },
                "Prayer": {
                    "type": "string"
                },
                "PreffeContPhone": {
                    "type": "string"
                },
                "PreffeContact": {
                    "type": "string"
                },
                "PreffeEmail": {
                    "type": "string"
                },
                "RefNo": {
                    "type": "string"
                },
                "Remarks": {
                    "type": "string"
                },
                "State": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "SubCategory": {
                    "type": "string"
                },
                "Subject": {
                    "type": "string"
                },
                "TransactionDate": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                }
            }
        },
        "models.ComplaintCategories": {
            "type": "object",
            "properties": {
                "CBNCategoryCode": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                }
            }
        },
        "models.ComplaintSubCategories": {
            "type": "object",
            "properties": {
                "CategoryID": {
                    "type": "integer"
                },
                "SubCategory": {
                    "type": "string"
                }
            }
        },
        "models.ResponseMessage": {
            "type": "object",
            "properties": {
                "ResponseCode": {
                    "type": "string"
                },
                "ResponseDescription": {
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Roles": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                }
            }
        },
        "models.TblCases": {
            "type": "object",
            "properties": {
                "AccountCurrency": {
                    "type": "string"
                },
                "AccountNumber": {
                    "type": "string"
                },
                "AccountType": {
                    "type": "string"
                },
                "ActionTaken": {
                    "type": "string"
                },
                "AddedBy": {
                    "type": "string"
                },
                "Address1": {
                    "type": "string"
                },
                "Address2": {
                    "type": "string"
                },
                "AmountRecovered": {
                    "type": "string"
                },
                "AmountRefunded": {
                    "type": "string"
                },
                "BranchName": {
                    "type": "string"
                },
                "CFirstName": {
                    "type": "string"
                },
                "CLastName": {
                    "type": "string"
                },
                "CMiddleName": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                },
                "CellPhone": {
                    "type": "string"
                },
                "City": {
                    "type": "string"
                },
                "ClientType": {
                    "type": "string"
                },
                "ComplaintChannelID": {
                    "type": "string"
                },
                "ComplaintLocation": {
                    "type": "string"
                },
                "ComplaintType": {
                    "type": "string"
                },
                "Country": {
                    "type": "string"
                },
                "DateClosed": {
                    "type": "string"
                },
                "DateCreated": {
                    "type": "string"
                },
                "DateReceived": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "DisputeAmount": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FullName": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "Implication": {
                    "type": "string"
                },
                "NameOfConsultant": {
                    "type": "string"
                },
                "OfficePhone": {
                    "type": "string"
                },
                "PosterCode": {
                    "type": "string"
                },
                "Prayer": {
                    "type": "string"
                },
                "PreffeContPhone": {
                    "type": "string"
                },
                "PreffeContact": {
                    "type": "string"
                },
                "PreffeEmail": {
                    "type": "string"
                },
                "RefNo": {
                    "type": "string"
                },
                "Remarks": {
                    "type": "string"
                },
                "State": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "SubCategory": {
                    "type": "string"
                },
                "Subject": {
                    "type": "string"
                },
                "TransactionDate": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "updatedby": {
                    "type": "string"
                }
            }
        },
        "models.TblComplaintCategories": {
            "type": "object",
            "properties": {
                "CBNCategoryCode": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                }
            }
        },
        "models.TblComplaintSubCategories": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "subCategory": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "DateAdded": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "MiddleName": {
                    "type": "string"
                },
                "OfficeLocation": {
                    "type": "string"
                },
                "RoleID": {
                    "type": "string"
                },
                "UpdatedBy": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                },
                "UserStatus": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Consumers Complaint Management System API",
	Description: "This service is meant to manage consumers complaint API.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
